#!/usr/bin/env python3
'''filtered_logger'''


import logging
import re

def filter_datum(fields, redaction, message, separator):
    '''returns the log message obfuscated'''
    return re.sub(fr'(?<=^|{separator})(?:{"|".join(fields)})(?={separator}|$)', redaction, message)
